---
title: "Document's title"
bibliography: refs.bib
csl: demographic-research.csl
link-citations: TRUE
output:
  bookdown::pdf_document2:
    toc: FALSE
    keep_tex: TRUE
    template: generic_article_template.tex
    #md_extensions: "-autolink_bare_uris"
    number_sections: TRUE
    citation_package: default # Can also be "natbib"
geometry: "margin=25mm"
papersize: letter
fontsize: 11pt
endfloat: FALSE # Set to TRUE to turn on latex endfloat package to place figures and tables at end of document
numberlines: FALSE
authblk: TRUE # FALSE = author affiliations in footnotes; TRUE = author affiliations in a block below author names
footnotehyper: FALSE # TRUE will give you enhanced table footnote capabilities. Set to FALSE to be able to use French blocks. Needed due to what appears to be a latex bug.
urlcolor: blue
linkcolor: blue
citecolor: blue
graphics: TRUE # Needed to be able to include images
tables: TRUE # Needed to be able to include tables
always_allow_html: true
abstract: "< N words"
---

```{r chunk-options, echo=FALSE}

## Global chunk options --------------------------------------------------------

knitr::opts_chunk$set(echo = FALSE, fig.pos = "H", out.extra = "")

```


```{r pkg-data, warning=FALSE, message=FALSE}

## Load packages ---------------------------------------------------------------

## Install/load packages
packages <- c("tidyverse", "ggplot2", "here")
for(p in packages){
    if(!require(p,character.only = TRUE)) install.packages(p)
    library(p,character.only = TRUE)
}



## Functions -------------------------------------------------------------------

## Script containing the functions computing
## the main elements required to run the kin dynamics



## Load data -------------------------------------------------------------------



```



# Introduction



# Data & Methods



# Preliminary Results



# Summary, Discussion and Next Steps




\newpage



# References {-}

<div id="refs"></div>
